Задача 11. За квадратною матрицею 
одержати послідовність чисел обходом матриці "спіраллю" за годинниковою стрілкою, розпочавши обхід у лівому верхньому куті.

In [4]:
import numpy as np

a=np.arange(36).reshape(6,-1)
n=a.shape[0]


def _AB(t,a, li):
    i=t
    for j in range(t, n-t-1):
        li.append(a[i,j])    
    return li


def _BC(t,a, li):   
    j=n-t-1
    for i in range(t, n-t-1):
        li.append(a[i,j])    
    return li


def _CD(t,a, li):
    i=n-t-1
    for j in range(n-t-1, t, -1):
        li.append(a[i,j])       
    return li


def _DA(t,a, li):   
    j=t
    for i in range(n-t-1, t, -1):
        li.append(a[i,j])      
    return li


def _a_spiral(t,a, li):
    _AB(t,a, li)
    _BC(t,a, li)
    _CD(t,a, li)
    _DA(t,a, li)
    return li


def spiral(a):
    m=n//2
    li=[]
    for t in range(m):
        _a_spiral(t, a, li)
    if n%2:
        li.append(a[m, m])
    return li
        
print(a, np.array(spiral(a)), sep='\n\n\n')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[ 0  1  2  3  4  5 11 17 23 29 35 34 33 32 31 30 24 18 12  6  7  8  9 10
 16 22 28 27 26 25 19 13 14 15 21 20]


In [ ]:
Задача 12. За квадратною матрицею одержати послідовність чисел обходом "змійкою"
трикутника над головною діагоналлю матриці, розпочавши обхід у правому верхньому куті та рухаючись діагоналями, починаючи вниз.

In [6]:
import numpy as np
b=int(7)
a=np.arange(b**2).reshape(b,-1)
n=a.shape[0]

def _down(t,a,li):
    n=a.shape[0]
    i=0
    j=t
    while j<n:
        li.append(a[i,j])              
        i+=1
        j+=1
    return li


def _up(t,a,li):
    n=a.shape[0]
    i=n-t-1
    j=n-1
    while i>=0:
        li.append(a[i,j])       
        i-=1
        j-=1     
    return li


def snake(a):
    li=[]
    n=a.shape[0]
    t=n-1
    for _ in range(n//2):
        _down(t,a,li)
        t-=1
        _up(t,a,li)
        t-=1
    if t>=0:
        _down(t,a,li)
    return li


print(a, np.array(snake(a)), sep='\n\n\n')

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]


[ 6 13  5  4 12 20 27 19 11  3  2 10 18 26 34 41 33 25 17  9  1  0  8 16
 24 32 40 48]


Задача 13. Написати функцію, яка обходить верхній чвертькутник матриці змійкою по горизонталі, починаючи з лівого верхнього кута

In [7]:
def _right(a,t,num):
    i=n-1-t
    for j in range(i,n-i):
        a[i,j]=num
        num+=1
    return num,t


def _left(a,t,num):
    i=n-1-t
    for j in range(n-i-1,i-1,-1):
        a[i,j]=num
        num+=1
    return num,t


def _horizontal(a,t,num):
    num,t=_right(a,t,num)
    t-=1
    num,t=_left(a,t,num)
    t-=1
    return num,t


def spiral(a):
    n=a.shape[0]
    m=(n+1)//4
    t=n-1
    num=0
    for _ in range(m):
        num,t=_horizontal(a,t,num)
    if n%2 and n>1:
        a[t,t]=num
        num+=1
    return num

import numpy as np
n=13
a=np.zeros((n,n),dtype=np.int)
spiral(a)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,  0],
       [ 0,  0, 24, 25, 26, 27, 28, 29, 30, 31, 32,  0,  0],
       [ 0,  0,  0, 39, 38, 37, 36, 35, 34, 33,  0,  0,  0],
       [ 0,  0,  0,  0, 40, 41, 42, 43, 44,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 47, 46, 45,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 48,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])